// Tell React Router the shape of the load context that workers/app.ts passes to
// createRequestHandler ({ cloudflare: { env, ctx } }). Without this, `context`
// in loaders/actions is `unknown`. `Env` is generated by `wrangler types` into
// worker-configuration.d.ts; ExecutionContext comes from the runtime types.
declare module "react-router" {
  interface AppLoadContext {
    cloudflare: {
      env: Env;
      ctx: ExecutionContext;
    };
  }
}

export {};
