import { getDb, pings } from "@survey/db";
import { desc } from "drizzle-orm";
import { Hono } from "hono";
import { createRequestHandler } from "react-router";

// One Worker: Hono owns routing. `/api/*` routes are handled here as a stable
// versioned API; everything else falls through to the React Router server
// handler (the framework app). Both share the same Cloudflare `env` bindings.
const app = new Hono<{ Bindings: Env }>();

// --- API (proves Hono + D1 read/write on the same Worker) ---
app.get("/api/health", (c) =>
  c.json({ ok: true, via: "hono", value: c.env.VALUE_FROM_CLOUDFLARE }),
);

app.get("/api/db-ping", async (c) => {
  const db = getDb(c.env.DB);
  const rows = await db.select().from(pings).orderBy(desc(pings.id)).limit(5);
  return c.json({ ok: true, count: rows.length, latest: rows });
});

app.post("/api/db-ping", async (c) => {
  const db = getDb(c.env.DB);
  const body = await c.req.json().catch(() => ({}) as { note?: string });
  const note = typeof body.note === "string" && body.note ? body.note : "ping";
  const inserted = await db.insert(pings).values({ note }).returning();
  return c.json({ ok: true, inserted: inserted[0] });
});

// --- Everything else → React Router (SSR framework app) ---
app.all("*", (c) => {
  const requestHandler = createRequestHandler(
    () => import("virtual:react-router/server-build"),
    import.meta.env.MODE,
  );
  return requestHandler(c.req.raw, {
    // Hono's bundled ExecutionContext type lags the runtime types generated by
    // `wrangler types` (missing tracing/abort); cast at this one boundary.
    cloudflare: { env: c.env, ctx: c.executionCtx as unknown as ExecutionContext },
  });
});

export default app;
